const val = [
  {
    "id": 1,
    "name": "White Cycle",
    "price": 10.99,
    "star": 4.1,
    "offer": 0 ,
    "isOffer":false,
    "productImage": "/Images/cycle.png",
  },
  {
    "id": 2,
    "name": "iPhone 14 pro",
    "price": 19.99,
    "star": 4.4,
    "isOffer":false,
    "offer": 0 ,
    "productImage": "/Images/phone.png",
  },
  {
    "id": 3,
    "name": "Blue abibbas Shoe",
    "price": 5.99,
    "star": 4.3,
    "isOffer":false,
    "offer": 0 ,
    "productImage": "/Images/shoe.png",
  },
  {
    "id": 4,
    "name": "Samsung Tablet",
    "price": 15.99,
    "star": 4.3,
    "isOffer":false,
    "offer": 0 ,
    "productImage": "/Images/tab.png",
  },
  {
    "id": 5,
    "name": "Titan Watch",
    "price": 12.99,
    "offer": 10 ,
    "star": 3.9,
    "isOffer":true,
    "productImage": "/Images/watch.png",
  },
  {
    "id": 6,
    "name": "Gaming Monitor",
    "price": 8.99,
    "star": 4.8,
    "isOffer":false,
    "offer": 0 ,
    "productImage": "/Images/monitor.png",
  }
]
export default val;